name = "imageGenerationWithDiffusionModels"
uuid = "0e980b57-2d15-48b5-bc5f-38b5886e7801"
authors = ["Kajetan Andrzejak <andrzejak@campus.tu-berlin.de>", "Eylul Bektur <bektur@campus.tu-berlin.de>", "Maxim Häffner <m.haefner@campus.tu-berlin.de>", "Maria Krzywnicka <maria.krzywnicka@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ImageView = "0.12.6"
Images = "0.26.2"
MAT = "0.10.7"
PkgTemplates = "0.7.55"
Random = "1.11.0"
julia = "1.11"
